[package]
name = "edist"
version = "0.1.0"
authors = ["Morten Torgund Dalfoss <mortendalfoss@gmail.com>"]
edition = "2018"

[lib]
name = "edist"
crate-type = ["cdylib"]

[dependencies]
rand = "0.6.5"
num_cpus = "1.10.0"

[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]
